<a href="https://colab.research.google.com/github/KARTHIKEYANK34/AIML_Course_KarthikeyanK/blob/Assignment-2/Numpy_and_Pandas_Practice_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



1.Create an array of numbers from 1 to 20 and reshape it into a 4×5 matrix.


In [2]:
array = np.arange(1,21)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
array=np.reshape(array,(4,5))
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])



2. Create an array of 10 zeros and replace the 5th element with 100.


In [4]:
array= np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:

array[4]=100
array



array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

3.Create a NumPy array of even numbers between 2 and 40."

In [6]:
array = np.arange(2,41,2)
array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

4. Generate a 1D array of 15 random integers between 1 and 100 and find its min, max, mean, and standard deviation.

In [7]:
np.random.seed(42)

In [8]:

random_integers = np.random.randint(1,101,15)
random_integers



array([ 52,  93,  15,  72,  61,  21,  83,  87,  75,  75,  88, 100,  24,
         3,  22])

In [9]:
random_integers.min()

np.int64(3)

In [10]:
random_integers.max()

np.int64(100)

In [11]:
np.int64(100)



np.int64(100)

In [12]:
random_integers.mean()

np.float64(58.06666666666667)

In [13]:
np.float64(58.06666666666667)

np.float64(58.06666666666667)

In [14]:
random_integers.std()

np.float64(31.4843170836247)



5.Given two arrays of sales and costs, calculate profit and profit percentage arrays.


In [20]:
sales = np.array([1000, 2000, 3000, 4000, 5000])
costs = np.array([500, 1000, 1500, 2000, 2500])
profit = sales - costs
profit

array([ 500, 1000, 1500, 2000, 2500])

In [21]:
profit_percentage = (profit / sales) * 100
profit_percentage.round(2)

array([50., 50., 50., 50., 50.])

6. Create a 6×6 random matrix and compute row sums, column sums, and total sum.

In [22]:
np.random.seed(10)

In [23]:
Matrix = np.random.randint(1,100, size=(6,6))
Matrix

array([[10, 16, 65, 29, 90, 94],
       [30,  9, 74,  1, 41, 37],
       [17, 12, 55, 89, 63, 34],
       [73, 79, 50, 52, 55, 78],
       [70, 14, 26, 14, 93, 87],
       [31, 31, 90, 13, 66, 32]])

In [24]:
print("Row sum :" ,Matrix.sum(axis=1))

Row sum : [304 192 270 387 304 263]


In [25]:
print("Column sums: ", Matrix.sum(axis=0))

Column sums:  [231 161 360 198 408 362]


In [26]:
print(" total sum:" ,Matrix.sum())

 total sum: 1720


7.Given stock prices, compute daily returns using vectorized NumPy operations.

In [27]:
prices = np.array([100, 102, 98, 105, 107, 103, 110])
daily_returns = (prices[1:] - prices[:-1]) / prices[:-1]
print("Stock Prices:", prices)
print("Daily Returns:", daily_returns.round(4))

Stock Prices: [100 102  98 105 107 103 110]
Daily Returns: [ 0.02   -0.0392  0.0714  0.019  -0.0374  0.068 ]




8.Convert an array of annual interest rates into monthly rates using vectorization.


In [28]:
annual_rates = np.array([0.06, 0.08, 0.12, 0.05])
monthly_rates = annual_rates / 12
print("Annual Interest Rates:", annual_rates)
print("Monthly Interest Rates:", monthly_rates.round(4))



Annual Interest Rates: [0.06 0.08 0.12 0.05]
Monthly Interest Rates: [0.005  0.0067 0.01   0.0042]


9.Normalize a given array of portfolio weights so that the sum becomes 1.

In [29]:
weights = np.array([30, 25, 20, 15, 10])
normalized_weights = weights / weights.sum()
print("Original weights:", weights)
print("Normalized (sum=1):", normalized_weights.round(4))



Original weights: [30 25 20 15 10]
Normalized (sum=1): [0.3  0.25 0.2  0.15 0.1 ]


10.  Create a Pandas Series from the following list: [1200, 1500, 1800, 2000, 2200]

In [30]:
import pandas as pd

data = [1200, 1500, 1800, 2000, 2200]
s = pd.Series(data, index=['Jan', 'Feb', 'Mar', 'Apr', 'May'])
print("Series:\n", s)
print("Mean:", s.mean())
print("Max:", s.max())
print("Index of max:", s.idxmax())  # or s.index[s.argmax()]

Series:
 Jan    1200
Feb    1500
Mar    1800
Apr    2000
May    2200
dtype: int64
Mean: 1740.0
Max: 2200
Index of max: May


11. Student Marks DataFrame

In [31]:
df_students = pd.DataFrame({
    'Name': ['KARTHIKEYAN K', 'AJITH', 'KUMAR', 'SARAVANAN'],
    'Math': [81, 82, 70, 95],
    'Science': [85, 89, 90, 87],
    'English': [90, 85, 88, 93]
})

print("Full DataFrame:\n", df_students)
print("Math column:\n", df_students['Math'])
print("First 2 rows:\n", df_students.head(2))
print("Shape:", df_students.shape)



Full DataFrame:
             Name  Math  Science  English
0  KARTHIKEYAN K    81       85       90
1          AJITH    82       89       85
2          KUMAR    70       90       88
3      SARAVANAN    95       87       93
Math column:
 0    81
1    82
2    70
3    95
Name: Math, dtype: int64
First 2 rows:
             Name  Math  Science  English
0  KARTHIKEYAN K    81       85       90
1          AJITH    82       89       85
Shape: (4, 4)


12. Account Balance Filtering

In [32]:
df = pd.DataFrame({
    "Account": [1001, 1002, 1003, 1004],
    "Balance": [5000, 15000, 7000, 12000]
})
print("Original DF:\n", df)
print("Balance > 8000:\n", df[df['Balance'] > 8000])
print("Balance between 6000 and 13000:\n",
      df[df['Balance'].between(6000, 13000)])

Original DF:
    Account  Balance
0     1001     5000
1     1002    15000
2     1003     7000
3     1004    12000
Balance > 8000:
    Account  Balance
1     1002    15000
3     1004    12000
Balance between 6000 and 13000:
    Account  Balance
2     1003     7000
3     1004    12000
